version: 2

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install
          command: pipenv install
      - run:
          name: Update Index
          command: cp README.md docs/index.md
      - run:
          name: Update Courses
          command: pipenv run python update.py
      - add_ssh_keys:
          fingerprints:
            - "a4:2f:c8:ed:e9:cd:b7:70:36:18:f8:55:c9:16:f2:5c"
      - run:
          name: Delete All SSH keys and Add the installed one
          command: ssh-add -D && ssh-add ~/.ssh/id_rsa_a42fc8ede9cdb7703618f855c916f25c
      - run:
          name: Deploy docs to gh-pages branch
          command: pipenv run mkdocs gh-deploy